In [1]:
keluarga = [1.73, 1.68, 1.71, 1.89]

In [2]:
keluarga

[1.73, 1.68, 1.71, 1.89]

In [3]:
max(keluarga)

1.89

In [4]:
paling_tinggi = max(keluarga)

In [5]:
paling_tinggi

1.89

In [6]:
len(keluarga)

4

In [7]:
round(1.68, 1)

1.7

In [8]:
round(1.68)

2

In [9]:
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



In [10]:
#Method
adik = 'dian'                        
# Object     tipe: str     contoh method: capitalize(), replace()
tinggi = 1.73                        
# Object     tipe: float   contoh method: bit_length(), conjugate()
keluarga = [1.73, 1.68, 1.71, 1.89]
# Object     tipe: list    contoh method: index(), count()

In [11]:
#List Method
keluarga = ["kakak", 1.73, "adik", 1.68, "ibu", 1.71, "ayah", 1.89]

In [12]:
keluarga.index('adik')

2

In [13]:
keluarga.count(1.73)

1

In [14]:
#str Method
adik

'dian'

In [15]:
adik.capitalize()

'Dian'

In [16]:
adik.replace('i', 'y')

'dyan'

In [19]:
adik.index('a')

2

In [20]:
keluarga.index('ibu')

4

In [21]:
keluarga.append('saya')

In [22]:
keluarga

['kakak', 1.73, 'adik', 1.68, 'ibu', 1.71, 'ayah', 1.89, 'saya']

In [23]:
keluarga.append(1.76)

In [24]:
keluarga

['kakak', 1.73, 'adik', 1.68, 'ibu', 1.71, 'ayah', 1.89, 'saya', 1.76]

In [25]:
type(keluarga)

list

In [26]:
keluarga.index('ibu')

4

In [27]:
import numpy

In [28]:
numpy.array([1,2,3])

array([1, 2, 3])

In [29]:
import numpy as np

In [30]:
np.array([1,2,3])

array([1, 2, 3])

In [31]:
from numpy import array

In [32]:
array([1,2,3])

array([1, 2, 3])

In [33]:
from numpy import array
keluarga = ["kakak", 1.73, "adik", 1.68, "ibu", 1.71, "ayah", 1.89]
keluarga_tambahan = keluarga + ['saya', 1.76]
print(str(len(keluarga_tambahan)) + " elemen pada keluarga_tambahan")
np_keluarga = array(keluarga_tambahan) 
#Menggunakan Numpy, tapi tidak begitu jelas
print(np_keluarga)

10 elemen pada keluarga_tambahan
['kakak' '1.73' 'adik' '1.68' 'ibu' '1.71' 'ayah' '1.89' 'saya' '1.76']


In [34]:
import numpy as np
keluarga = ["kakak", 1.73, "adik", 1.68, "ibu", 1.71, "ayah", 1.89]
keluarga_tambahan = keluarga + ['saya', 1.76]
print(str(len(keluarga_tambahan)) + " elemen pada keluarga_tambahan")
np_keluarga = np.array(keluarga_tambahan) 
#Jelas menggunakan Numpy dengan alias np
print(np_keluarga)

10 elemen pada keluarga_tambahan
['kakak' '1.73' 'adik' '1.68' 'ibu' '1.71' 'ayah' '1.89' 'saya' '1.76']
