In [1]:
tinggi = [1.73, 1.68, 1.71, 1.89, 1.69]

In [2]:
tinggi

[1.73, 1.68, 1.71, 1.89, 1.69]

In [3]:
berat = [65.4, 59.2, 63.6, 88.4, 68.7]

In [4]:
berat / tinggi ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [6]:
import numpy as np
np_tinggi = np.array(tinggi)
np_tinggi

array([1.73, 1.68, 1.71, 1.89, 1.69])

In [7]:
np_berat = np.array(berat)

In [8]:
np_berat

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [9]:
bmi = np_berat / np_tinggi ** 2

In [10]:
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 24.05377963])

In [11]:
np.array([1.0, 'is', True]) 
#Numpy hanya dapat menampung satu tipe

array(['1.0', 'is', 'True'], dtype='<U32')

In [12]:
python_list = [1,2,3]
numpy_array = np.array([1,2,3])

In [13]:
python_list + python_list

[1, 2, 3, 1, 2, 3]

In [14]:
numpy_array + numpy_array 

array([2, 4, 6])

In [15]:
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 24.05377963])

In [16]:
bmi > 23

array([False, False, False,  True,  True])

In [17]:
bmi[bmi > 23]

array([24.7473475 , 24.05377963])

In [18]:
import numpy as np
np_tinggi = np.array([1.73, 1.68, 1.71, 1.89, 1.69])
np_berat = np.array([ 65.4,  59.2,  63.6,  88.4,  68.7])

In [19]:
type(np_tinggi)

numpy.ndarray

In [20]:
type(np_berat)

numpy.ndarray

In [21]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.69], [ 65.4,  59.2,  63.6,  88.4,  68.7]])

In [22]:
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.69],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [23]:
np_2d[0]

array([1.73, 1.68, 1.71, 1.89, 1.69])

In [24]:
np_2d[0][2]

1.71

In [25]:
np_2d[0,2]

1.71

In [26]:
np_2d[:,1:3]

array([[ 1.68,  1.71],
       [59.2 , 63.6 ]])

In [27]:
np_2d[1,:]

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [28]:
tinggi = np.round(np.random.normal(1.75, 0.20, 5000), 2)
berat = np.round(np.random.normal(60.32, 15, 5000), 2)
# np.random.normal(distribution_mean, distribution_standard_deviation, jumlah_sample)

In [29]:
np_city = np.column_stack((tinggi, berat))

In [30]:
np_city

array([[ 1.68, 58.42],
       [ 1.78, 55.88],
       [ 1.44, 50.12],
       ...,
       [ 1.95, 50.82],
       [ 1.61, 66.43],
       [ 2.02, 62.98]])

In [31]:
np.mean(np_city[:,0])

1.7491160000000003

In [32]:
np.median(np_city[:,0])

1.75

In [33]:
np.corrcoef(np_city[:,0], np_city[:,1])

array([[ 1.        , -0.00951445],
       [-0.00951445,  1.        ]])

In [34]:
np.std(np_city[:,0])

0.1983203936664104